### PR TITLE
Added documentation about redux containers in the flow

### PR DESCRIPTION
**Pull request by orielz**

### CODE REVIEW

**Comment by tikider** [comment]
Thank you for the your PR.
To have translations in the components you can just require the `Translate` and `Localize` components and use them.
To update the localisation object you can `store.dispatch(loadTranslations(translationsObject);` whenever you want.
So it is not needed to pass on the i18n state object to components.

**Comment by orielz** [comment]
React re-render the component only when one of his properties had been changed, so you have to pass the object that changed to the component via redux-connect (which is the translation object), otherwise, the component will not be re-rendered and updated with the correct translations and only the initial render will display the correct translations values.

**Comment by tikider** [comment]
The problem you are describing is definitely valid. However this solution is a kind of a hack to solve it. Because you will need to include i18n state for all connected components to the store. A better solution is let react-i18nify handle that.
I made a PR for that: https://github.com/zoover/react-i18nify/pull/9
When merged I will update the project to take advantage of it.
Thank you very much for this valuable contribution.

**Comment by tikider** [comment]
Solved from v0.1.0.

**Pull request closed without merging**
